### ISSUE TITLE
Warning with 4.25.1

### ISSUE THREAD

**Issue by Kassec** [yaakuro/CodeLiteSourceCodeAccess#4]
Hey yaakuro, thanks for the great job ! Having support for a decent IDE on Linux is premium !!!!!

Compiling UE 4.25.1 with this git repo gives a deprecation warning:
WARNING: The 'Developer' module type has been deprecated in 4.24. Use 'DeveloperTool' for modules that can be loaded by game/client/server targets in non-shipping configurations, or 'UncookedOnly' for modules that should only be loaded by uncooked editor and program targets (eg. modules containing blueprint nodes)
/home/kassec/dev/UnrealEngine/Engine/Plugins/Developer/CodeLiteSourceCodeAccess/CodeLiteSourceCodeAccess.uplugin: warning: The 'Developer' module type has been deprecated in 4.24.

**Comment by yaakuro** [comment]
I made new branch for 4.25. That should fix that issue.
